---
apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
    - image: backend-img
      context: backend
      hooks:
        # after build lifecycle hook
        after:
        - command: 
          - /bin/sh 
          - -c
          - "cat _kustomization.yaml | envsubst > kustomization.yaml"
  tagPolicy:
    sha256: {}

manifests:
  kustomize:
    paths:
    - kubernetes/kustomize/backend/overlays/dev

deploy:
  kubectl: {}

profiles:
  - name: qa
    activation:
      - env: KUBECONFIG='/home/nattawat.ujj/.kube/rke2-gong-kubeadm.conf'
    deploy:
      kubeContext: rke2-kubeadm
    manifests:
      kustomize:
        paths:
        - kubernetes/kustomize/backend/overlays/qa