---
apiVersion: skaffold/v4beta11
kind: Config
build:
  googleCloudBuild: {}
  artifacts:
    - image: backend-img
      context: backend
      kaniko:
        cache: {}
  tagPolicy:
    sha256: {}

manifests:
  kustomize:
    paths:
    - kubernetes/kustomize/backend/overlays/dev

deploy:
  kubectl: {}

profiles:
  - name: qa
    activation:
      - env: KUBECONFIG='/home/nattawat.ujj/.kube/rke2-gong-kubeadm.conf'
    deploy:
      kubeContext: rke2-kubeadm
    manifests:
      kustomize:
        paths:
        - kubernetes/kustomize/backend/overlays/qa